# Generated by Django 5.2.7 on 2025-11-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bruker',
            fields=[
                ('brukernavn', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fulltnavn', models.CharField(max_length=64)),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Lager',
            fields=[
                ('lagernavn', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lagertype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lagertype', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Legemiddel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ab_prep', models.CharField(max_length=1)),
                ('beholdning', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lokasjoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasjoner', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Preparat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparatnavn', models.CharField(max_length=64)),
                ('virkestoff', models.CharField(max_length=64)),
                ('ab_prep', models.CharField(max_length=1)),
                ('styrke', models.PositiveIntegerField()),
                ('styrekbenevnelse', models.CharField(max_length=64)),
                ('legemiddelform', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Stillingstype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stillingstype', models.CharField(default='Sykepleier', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sykepleier',
            fields=[
                ('signatur', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fulltNavn', models.CharField(max_length=64)),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='BrukerLagerTilgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fikkTilgang', models.DateTimeField()),
                ('avsluttTilgang', models.DateTimeField()),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testnr.bruker')),
                ('lager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testnr.lager')),
            ],
        ),
        migrations.AddField(
            model_name='lager',
            name='lagertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testnr.lagertype'),
        ),
        migrations.CreateModel(
            name='LegemiddelLogg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparat', models.CharField(max_length=64)),
                ('preparatbeholdningStart', models.PositiveIntegerField()),
                ('preparatbeholdningSlutt', models.PositiveIntegerField()),
                ('tidspunkt', models.DateTimeField()),
                ('kommentar', models.TextField(null=True)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testnr.bruker')),
            ],
        ),
        migrations.AddField(
            model_name='lager',
            name='lokasjon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testnr.lokasjoner'),
        ),
        migrations.AddField(
            model_name='bruker',
            name='stillingstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testnr.stillingstype'),
        ),
        migrations.CreateModel(
            name='LagerPreparatBeholdning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beholdning', models.PositiveIntegerField()),
                ('lager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testnr.lager')),
                ('preparat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testnr.preparat')),
            ],
            options={
                'unique_together': {('lager', 'preparat')},
            },
        ),
    ]
