# Generated by Django 5.1.7 on 2025-04-03 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legemiddel',
            name='beholdning',
        ),
        migrations.CreateModel(
            name='Lager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beholdning', models.IntegerField()),
                ('lm_lager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legemiddel', to='testnr.legemiddel')),
            ],
        ),
    ]
