# Generated by Django 5.2.7 on 2025-11-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegemiddelLogg1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparat', models.CharField(max_length=64)),
                ('preparatbeholdningStart', models.PositiveIntegerField()),
                ('preparatbeholdningSlutt', models.PositiveIntegerField()),
                ('tidspunkt', models.DateTimeField()),
                ('kommentar', models.TextField(null=True)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testnr.bruker')),
            ],
        ),
    ]
