# Generated by Django 5.1.7 on 2025-04-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0002_remove_legemiddel_beholdning_lager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lager',
            name='lm_lager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legemiddel', to='testnr.legemiddel', unique=True),
        ),
    ]
