# Generated by Django 5.2.7 on 2025-11-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0002_legemiddellogg1'),
    ]

    