# Generated by Django 5.1.7 on 2025-04-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0003_alter_lager_lm_lager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lager',
            name='lm_lager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legemiddel', to='testnr.legemiddel'),
        ),
    ]
