# Generated by Django 5.2.7 on 2025-11-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0004_delete_legemiddellogg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legemiddellogg1',
            name='tidspunkt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
