# Generated by Django 5.1.7 on 2025-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0004_alter_lager_lm_lager'),
    ]

    operations = [
        migrations.AddField(
            model_name='lager',
            name='lokasjon',
            field=models.CharField(default='mottak', max_length=64),
        ),
    ]
