# Generated by Django 5.2.7 on 2025-11-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0005_alter_legemiddellogg1_tidspunkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='legemiddellogg1',
            name='lager',
            field=models.CharField(default='test', max_length=64),
        ),
    ]
