# Generated by Django 5.2.7 on 2025-11-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0006_legemiddellogg1_lager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legemiddellogg1',
            name='kommentar',
            field=models.TextField(default='Ingen kommentar'),
        ),
    ]
