# Generated by Django 5.1.7 on 2025-09-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0006_alter_lager_lm_lager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lager',
            name='lm_lager',
        ),
        migrations.AddField(
            model_name='legemiddel',
            name='beholdning',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lager',
            name='beholdning',
            field=models.IntegerField(default=0),
        ),
    ]
