# Generated by Django 5.1.7 on 2025-10-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testnr', '0007_remove_lager_lm_lager_legemiddel_beholdning_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sykepleier',
            fields=[
                ('signatur', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fulltNavn', models.CharField(max_length=64)),
                ('pin', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Lager',
        ),
    ]
